apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helpdesk-llm-gcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeiglerit/automagic.git
    targetRevision: HEAD
    path: manifests/gcp
  destination:
    name: gcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
