apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helpdesk-llm-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeiglerit/automagic.git
    targetRevision: HEAD
    path: clusters/helpdesk-llm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
