apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-eks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeiglerit/automagic.git
    path: argo/helm/nginx-webserver
    targetRevision: HEAD
  destination:
    server: https://2EB33A666BE446F7BF86E1D3B9B10D5A.gr7.us-east-1.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
