apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeiglerit/automagic.git
    targetRevision: master
    path: argo-apps
    directory:
      recurse: false
      include: "*.yaml"
      exclude: "agentic-helpdesk-cluster3.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
