$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

command: >-
  python scripts/insightedge/train.py
  --training_config scripts/insightedge/config.json

code: .

environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:cpu-cluster

display_name: insightedge-training-job
experiment_name: insightedge-experiment
description: Config-driven MNIST training with TensorBoard logging

resources:
  instance_count: 1

outputs:
  model_output:
    mode: upload
    path: outputs/mnist_model.keras
