apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-webserver.fullname" . }}-html
data: 
index.html: |
  <html>
    <head><title>NGINX Web Server</title></head>    
    <body> 
      <h1>NGINX Web Server</h1>
      <p>Deployed via Helm + Argo CD across AWS, Azure, and GCP.</p>
    </body>
  </html>
