apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helpdesk-llm-root
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GIT_URL
    path: argo-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
